
apiVersion: v1
kind: Secret
metadata:
  name: zero-ssl-eabsecret
data:
  secret: bThONEZqaFdlTDBGNDY2Ymd3R244dkdmenF6amk3R3d6Vlk4dUk4VFk4LTQtaHdBcE5mYjA4QnYtVzZXLXFKUnREa3dIUUl1cExMb0FVWnJDUmYwMFEK
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: JcLOlLuYIs3urFWcqeda7w
      keySecretRef:
        name: zero-ssl-eabsecret
        key: secret
      keyAlgorithm: HS512
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx
          podTemplate:
            spec:
              nodeSelector:
                "kubernetes.io/os": linux
