apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ssp-senslas.fullname" . }}
  labels:
    {{- include "ssp-senslas.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ssp-senslas.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "ssp-senslas.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ssp-senslas.serviceAccountName" . }}
      hostPID: true
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: dev-tpm0
              mountPath: /dev/tpm0
            - name: dev-tpmrm0
              mountPath: /dev/tpmrm0
            - name: sys
              mountPath: /sys
              #- name: app
              #mountPath: /app
          ports:
            - name: http
              containerPort: {{ .Values.image.containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
            #command: ["/SensAttest/SensAttest"]
            #args: [" -port={{ .Values.image.containerPort }}", "http"]
          command: ["/bin/sh"]
          args: ["-c", "/SensAttest/SensAttest -port={{ .Values.image.containerPort }} http"]
      volumes:
        - name: dev-tpm0
          hostPath:
            path: /dev/tpm0
        - name: dev-tpmrm0
          hostPath:
            path: /dev/tpmrm0
        - name: sys
          hostPath:
            path: /sys
        #- name: app
          #emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
