# Default values for sens-lls.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

#checkrls:
#  env:
#    SENSRLS_API_PORT: 9202
#  serviceEnv:
#    SENSRLS_HOST: "ctrl-rls"

image:
  repository: sensoriant.azurecr.io/nference/senslls
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "VERSION_1_2_0"
  containerPort: 9102
  env:
    SENSLLS_PORT: 9102
    SENSRLS_MTLS_PORT: 9201
    SENSRLS_API_PORT: 9202
    SENSLLS_URL: "http://localhost"
    SENSLLS_HOSTNAME: localhost
  serviceEnv:
    SENSRLS_HOST: "ctrl-rls"
    SENSLLS_HOST: "ctrl-lls"
    SENSRLS_URL: "ctrl-rls"
    #urlEnv:

imagePullSecrets:
- name: sens-reg-cred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

svcenabled: true
service:
  type: ClusterIP
  port: 9102
  targetPort: 9102

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { sensmode: controller }

tolerations: []

affinity: {}
