{{- if .Values.svcenabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sens-mdb.fullname" . }}
  labels:
    {{- include "sens-mdb.labels" . | nindent 4 }}
spec:
  {{- if .Values.headless }}
  clusterIP: None
  {{- end }}
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sens-mdb.selectorLabels" . | nindent 4 }}
{{- end }}
