# Default values for sens-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sensoriant.azurecr.io/nference/ras-agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "VERSION_1_1_2"
  #containerPort: 5010
  env: 
     SENSORIANT_SPIRE_TRUST_DOMAIN: "secure-cloud-dev.sensoriant.com"
     SENSORIANT_SPIRE_SERVER_PORT: "5010"
     SENSORIANT_ATTESTATION_DOCKER_PORT: "9005"
     SENSORIANT_PLATFORM_SIGNING_KEY: ""
     SENSORIANT_PLATFORM_PROVIDER: "AZURE"
     RELEASE_TAG: "VERSION_1_1_2"
     GCS_BUCKET_NAME: "sensoriant-dev-storage"
     SENSCLI_DREG: "nferalgos.azurecr.io"
     LOG_LEVEL: "INFO"
  serviceEnv: 
     SENSORIANT_SPIRE_SERVER_HOSTNAME: "ctrl-ras"
     SENSORIANT_ATTESTATION_HOST: "ssp-senslas"

imagePullSecrets:
- name: sens-reg-cred

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

svcenabled: false
service:
  type: ClusterIP
  port: 5010
  targetPort: 5010

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: { sensmode: sandbox }

tolerations: []

affinity: {}

livenessProbe: {}

readinessProbe: {}

## Container images within the pod
checksspsenslas:
  name: "ssp-senslas"
  port: "9005"
checkrasserver:
  name: "ctrl-ras"
  port: "5010"
