{{- if .Values.svcenabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ssp-ras.fullname" . }}
  labels:
    {{- include "ssp-ras.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "ssp-ras.selectorLabels" . | nindent 4 }}
{{- end }}
