{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
 labels:
   {{- include "sens-pmgr.labels" . | nindent 4 }}
 name: {{ template "sens-pmgr.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "sens-pmgr.serviceAccountName" . }}
roleRef:
 kind: Role
 name: {{ template "sens-pmgr.fullname" . }}
 apiGroup: rbac.authorization.k8s.io
{{- end }}
