{{- if .Values.svcenabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "algo-prep.fullname" . }}
  labels:
    {{- include "algo-prep.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "algo-prep.selectorLabels" . | nindent 4 }}
{{- end }}
